Tradeplaza/Tradeplaza/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('',include('core.urls')),
    path('items/',include ('item.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('inbox/',include('conversation.urls'))
] 

Tradeplaza/conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('',views.inbox,name='inbox'),
    path('<int:pk>/',views.detail,name='detail'),
    path('new/<int:item_pk>/',views.new_conversation,name='new'),
]

Tradeplaza/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('policy/',views.policy,name='policy'),
    path('license/',views.license,name='license'),
    path('signup/',views.signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm),name='login'),
    path('logout/',views.logout_view, name='logout'),
] 

Tradeplaza/item/urls.py
from django.urls import path

from .import views

app_name = 'item'

urlpatterns = [
    path('',views.items,name='items'),
    path('new/',views.new,name='new'),
    path('<int:pk>/',views.detail,name='detail'),
    path('<int:pk>/delete/',views.delete,name='delete'),    
    path('<int:pk>/edit/',views.edit,name='edit'),
] 

Tradeplaza/item/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='media/item_images',height_field=None, width_field=None, max_length=None,blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    
    def __str__(self):
        return self.name

Tradeplaza/item/forms.py
from django import forms
from .models import Item, Category

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category','name','description','price','image',)


    category = forms.ModelChoiceField(queryset=Category.objects.all(),widget=forms.Select(attrs={
        'class': 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
    }))
       
    name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Type product name',
        'class': 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
    }))

    description = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Write product description here',
        'class': 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
    }))

    price = forms.DecimalField(widget=forms.NumberInput(attrs={
        'placeholder': 'eg.$49.99',
        'class': 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
    }))

    image = forms.ImageField(widget=forms.ClearableFileInput(attrs={
        'class': 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
    }))

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name','description','price','image','is_sold')
    name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Type product name',
        'class': 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'

        
    }))

    description = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Write product description here',
        'class': 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'

        
    }))

    price = forms.DecimalField(widget=forms.NumberInput(attrs={
        'placeholder': 'eg.$49.99',
        'class': 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'

        
    }))

    image = forms.ImageField(widget=forms.ClearableFileInput(attrs={
         'class': 'bg-gray-50 border border-gray-300 text-white sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 placeholder:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
         #this part needs a little bit of polishing
    }))
    
    is_sold = forms.BooleanField(required=False,widget=forms.CheckboxInput())


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['image'].widget.initial_text = 'Current Image'
        self.fields['image'].widget.input_text = 'Upload the new Image'

    
       

Tradeplaza/item/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render,get_object_or_404,redirect

from .forms import NewItemForm, EditItemForm
from .models import Category,Item


def items(request):
    query = request.GET.get('query','')
    category_id = request.GET.get('category',0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    # potential search histoy option
    #search_history=request.session.get('search_history', [])  
    # if query and query not in search_history:
    #     search_history.append(query)    
    # max_history_length = 10
    # if len(search_history) > max_history_length:
    #     search_history = search_history[-max_history_length:]
    if category_id:
        items = items.filter(category_id=category_id)
    if query:
        items = items.filter(Q(name__icontains=query))
    
    return render(request, 'item/items.html',{
        'items':items,
        'query':query,
        'categories':categories,
        'category_id':int(category_id),
      #  'search_history': search_history,
    })

def detail(request,pk):
    item = get_object_or_404(Item,pk=pk)
    related_items = Item.objects.filter(category=item.category,is_sold=False).exclude(pk=pk)[0:3]
    return render(request,'item/detail.html',{
        'item' : item,
        'related_items' : related_items,
    })

@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST,request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            return redirect('item:detail',pk=item.id)
    else:
        form = NewItemForm()
    

    return render(request, 'item/form.html',{
        'form' : form,
        'title' : 'List Item',
    })

@login_required
def edit(request,pk):
    item = get_object_or_404(Item,pk=pk,created_by=request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST,request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect('item:detail',pk=item.id)
    else:
        form = EditItemForm(instance=item)
    

    return render(request, 'item/editform.html',{
        'form' : form,
        'title' : 'Edit Item',
    })


@login_required
def delete(request,pk):
    item = get_object_or_404(Item,pk=pk,created_by=request.user)
    item.delete()
    return redirect('dashboard:index')

Tradeplaza/item/templates/item/detail.html
{% extends "core/base.html" %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<div class="bg-gray-900 p-8">

    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div class="w-full max-h-screen border border-gray-200 rounded-lg p-8 shadow bg-gray-800 dark:border-gray-700 hover:shadow-md transition-shadow" style="aspect-ratio: 16 / 9; overflow: hidden;">
            <img src="{{ item.image.url }}" style="width: 100%; height: 100%; object-fit: cover;" alt="{{ item.name }}">
        </div>
        <div class="w-full border border-gray-200 rounded-lg p-8 shadow bg-gray-800 dark:border-gray-700 hover:shadow-md transition-shadow">
            <h1 class="mb-6 text-3xl text-white"><strong>{{ item.name }}</strong></h1>
            <p class="text-white text-2xl">Price: <strong>${{ item.price }}</strong> </p><br>
            {% if request.user == item.created_by %}
                <p class="text-white text-2xl">Seller: <strong>You</strong></p><br>
            {% else %}
                <p class="text-white"><strong>Seller: </strong> {{ item.created_by.username }}</p><br>
            {% endif %}
            {% if item.description %}
                <p class="text-white ">
                    <strong class=" text-2xl text-white">Description:</strong>
                    <br>
                    <br>
                    {{ item.description }}
                </p>
            {% endif %}
            <br> 
            {% if request.user == item.created_by %}
                <div class="py-4 rounded-xl">
                    <a href="{% url 'item:edit' item.id %}" class="text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 shadow-lg shadow-blue-500/50 dark:shadow-lg  font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2 ">
                        Edit Item 
                    </a>
                    <a href="{% url 'item:delete' item.id %}" data-modal-target="popup-modal" data-modal-toggle="popup-modal" class="ml-1 text-white bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 shadow-lg shadow-red-500/50 dark:shadow-lg  font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2">
                        Delete Item
                    </a> 
                </div>
            {% else %}
                <a href="{% url 'conversation:new' item.id %}" class="py-2.5 px-5 me-2 mb-2 text-sm font-medium text-white focus:outline-none bg-blue-700 hover:bg-blue-800 rounded-lg border border-gray-200 focus:z-10 focus:ring-4 focus:ring-gray-200 text-center">
                    Contact Seller
                </a>
            {% endif %}
        </div>
    </div>

    <div class="mt-6">
        <h2 class="mb-12 text-3xl font-semibold text-white text-center">Related items</h2>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {% for item in related_items %}
                <div class="w-full max-w-sm border border-gray-200 rounded-lg shadow bg-gray-800 dark:border-gray-700 hover:shadow-md transition-shadow">
                    <a href="{% url 'item:detail' item.id%}">
                        <img class="p-8 rounded-t-lg w-full h-[280px]"
                            src="{{item.image.url}}" alt="{{item.name}}" />
                    </a>
                    <div class="px-5 pb-5">
                        <a href="#">
                            <h5 class="text-xl font-semibold tracking-tight text-gray-900 dark:text-white">{{item.name}}</h5>
                        </a>
                        <div class="flex items-center mt-2.5 mb-5">
                            <div
                                class="flex items-center space-x-1 rtl:space-x-reverse">
                                <svg class="w-4 h-4 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                                <svg class="w-4 h-4 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                                <svg class="w-4 h-4 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                                <svg class="w-4 h-4 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                                <svg class="w-4 h-4 text-gray-200 dark:text-gray-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                            </div>
                            <span class="bg-blue-100 text-blue-800 text-xs font-semibold px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800 ms-3">5.0</span>
                        </div>
                        <div class="flex items-center justify-between">
                            <span class="text-3xl font-bold text-gray-900 dark:text-white">${{item.price}}</span>
                            <a href="{% url 'conversation:new' item.id %}"
                                class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Contact Seller
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

Tradeplaza/item/templates/item/editform.html
{% extends "core/base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="bg-gray-900 px-6 py-8 ">
    <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto lg:py-0">
        <div class="w-full rounded-lg shadow md:mt-0 sm:max-w-lg mx-4 md:mx-auto bg-gray-800">
            <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                <h1 class="text-xl font-bold leading-tight tracking-tight text-white md:text-2xl">
                    Edit Item
                </h1>
                <form method="post" action="." enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="grid gap-4 mb-4 sm:grid-cols-2">
                        <div>
                            <label for="name" class="block mb-2 text-sm font-medium text-white">Name</label>
                            {{ form.name }}
                        </div>
                        <div>
                            <label for="brand" class="block mb-2 text-sm font-medium text-white">Image</label>
                            {{ form.image }}
                        </div>
                        <div>
                            <label for="price" class="block mb-2 text-sm font-medium text-white">Price</label>
                            {{ form.price }}
                        </div>
                        <div>
                            <label for="is_sold" class="block mb-2 text-sm font-medium text-white">Stock</label>
                            <div class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                                Out of stock &nbsp; {{ form.is_sold }}
                            </div>
                        </div>
                        <div class="sm:col-span-2">
                            <label for="description" class="block mb-2 text-sm font-medium text-white">Description</label>
                            {{ form.description }}
                        </div>
                    </div>
                    <button class="w-full mt-3 text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
                        Submit
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Tradeplaza/item/templates/item/form.html
{% extends "core/base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="bg-gray-900 px-6 py-8 ">
    <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto lg:py-0">
        <div class="w-full rounded-lg shadow md:mt-0 sm:max-w-lg mx-4 md:mx-auto bg-gray-800">
            <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                <h1 class="text-xl font-bold leading-tight tracking-tight text-white md:text-2xl">
                    List an Item
                </h1>
                <form method="post" action="." enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="grid gap-4 mb-4 sm:grid-cols-2">
                        <div>
                            <label for="name" class="block mb-2 text-sm font-medium text-white">Name</label>
                            {{ form.name }}
                        </div>
                        <div>
                            <label for="image" class="block mb-2 text-sm font-medium text-white">Image</label>
                            {{ form.image }}
                        </div>
                        <div>
                            <label for="price" class="block mb-2 text-sm font-medium text-white">Price</label>
                            {{ form.price }}
                        </div>
                        <div>
                            <label for="category" class="block mb-2 text-sm font-medium text-white">Category</label>
                            {{ form.category }}
                        </div>
                        <div class="sm:col-span-2">
                            <label for="description" class="block mb-2 text-sm font-medium text-white">Description</label>
                            {{ form.description }}
                        </div>
                    </div>
                    {% if form.errors or form.non_field_errors %}
                        <div class="mb-3 p-6 bg-red-100 rounded-xl">
                            {% for field in form %}
                                {{ field.errors }}
                            {% endfor %}
                            {{ form.non_field_errors }}
                        </div>
                    {% endif %}
                    <button class="w-full  mt-3 text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
                        Submit
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Tradeplaza/item/templates/item/items.html
{% extends "core/base.html" %}

{% block title %}Search results{% endblock %}

{% block content %}

    {% comment %} <div class="lg:w-1/4 mt-2 pb-6 py-12 bg-gray-100 rounded-xl">
        <hr>
        <div class="flex flex-col">
            <h2 class="font-semibold text-xl self-start pt-4 pb-6">Categories</h2>
            <hr class="my-2">
            <ul class="flex flex-col self-start text-[16px]">
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl transition duration-300 ease-in-out hover:bg-blue-100 transform hover:scale-105">
                        <a href="{% url 'item:items' %}?query={{toy}}&category={{category.id}}">{{category.name}}</a>
                    </li>    
                {% endfor %}
            </ul>
        </div>
    </div> 
    Add a sidebar for the user to view all the categories available
    {% endcomment %}
    <div class="flex justify-center items-center bg-gray-900 min-h-screen">
        <div class="w-full px-6 py-12 flex flex-col items-center justify-center">
            {% if items %}
            <h2 class="mb-6 text-white text-2xl font-semibold text-center">Showing search results for '{{ query }}'</h2>
            <div class="grid md:grid-cols-1 lg:grid-cols-3 gap-3 flex">
                {% for item in items %}
                <div class="w-full max-w-sm border border-gray-200 rounded-lg shadow bg-gray-800 dark:border-gray-700 hover:shadow-md transition-shadow">
                    <a href="{% url 'item:detail' item.id%}">
                        <img class="p-8 rounded-t-lg w-full h-[280px]"
                            src="{{item.image.url}}" alt="{{item.name}}" />
                    </a>
                    <div class="px-5 pb-5">
                        <a href="{% url 'item:detail' item.id%}">
                            <h5 class="text-xl font-semibold tracking-tight text-gray-900 dark:text-white">{{item.name}}</h5>
                        </a>
                        <div class="flex items-center mt-2.5 mb-5">
                            <div
                                class="flex items-center space-x-1 rtl:space-x-reverse">
                                <svg class="w-4 h-4 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                                <svg class="w-4 h-4 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                                <svg class="w-4 h-4 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                                <svg class="w-4 h-4 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                                <svg class="w-4 h-4 text-gray-200 dark:text-gray-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                            </div>
                            <span class="bg-blue-100 text-blue-800 text-xs font-semibold px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800 ms-3">5.0</span>
                        </div>
                        <div class="flex items-center justify-between">
                            <span class="text-3xl font-bold text-gray-900 dark:text-white">${{item.price}}</span>
                            <a href="{% url 'conversation:new' item.id %}"
                                class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Contact Seller
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% else %}
            <h2 class="m-auto h-screen text-white text-2xl font-semibold">Sorry. No results found for "{{ query }}"</h2>
            {% endif %}
        </div>
    </div>
{% endblock %}