Tradeplaza/Tradeplaza/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('',include('core.urls')),
    path('items/',include ('item.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('inbox/',include('conversation.urls'))
] 

Tradeplaza/conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('',views.inbox,name='inbox'),
    path('<int:pk>/',views.detail,name='detail'),
    path('new/<int:item_pk>/',views.new_conversation,name='new'),
]

Tradeplaza/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('policy/',views.policy,name='policy'),
    path('license/',views.license,name='license'),
    path('signup/',views.signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm),name='login'),
    path('logout/',views.logout_view, name='logout'),
] 

Tradeplaza/dashboard/urls.py
from django.urls import path

from .import views

app_name = 'dashboard'

urlpatterns = [
    path('',views.index,name='index'),
] 

Tradeplaza/item/urls.py
from django.urls import path

from .import views

app_name = 'item'

urlpatterns = [
    path('',views.items,name='items'),
    path('new/',views.new,name='new'),
    path('<int:pk>/',views.detail,name='detail'),
    path('<int:pk>/delete/',views.delete,name='delete'),    
    path('<int:pk>/edit/',views.edit,name='edit'),
] 

Tradeplaza/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'johndoe',
        'class': 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': '*******',
        'class': 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email','password1','password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'johndoe',
        'class': 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'johndoe@example.com',
        'class': 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': '*******',
        'class': 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': '*******',
        'class': 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
    }))

    # image = forms.ImageField(widget=forms.ClearableFileInput(attrs={
    #     'class': 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'

    # }))

Tradeplaza/core/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import logout
from item.models import Category,Item
from .forms import SignupForm
import random

def index (request):
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()
    random_items = random.sample(list(items),6)
    return render(request, 'core/index.html', {
        'random_items': random_items,
        'categories': categories,
        'items': items,
    })

def about (request):
    return render(request, 'core/about.html')

def license (request):
    return render(request, 'core/license.html')

def policy (request):
    return render(request, 'core/policy.html')

def signup(request):
    if request.method == 'POST':
        form= SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
        
    else:
        form = SignupForm()
    
    return render(request,'core/signup.html',{
        'form':form
    })

def logout_view(request):
    logout(request)
    return redirect('/') 

Tradeplaza/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %} | TradePlaza</title>
    <link rel="icon" href="https://cdn.jsdelivr.net/gh/Raaxxy/Trade-plaza@main/Tradeplaza/media/logo.jpeg" type="image/png">
</head>

<body class="font-sans">
    <nav class="border-gray-200 bg-gray-900">
        <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
            <a href="/" class="flex items-center space-x-3 rtl:space-x-reverse">
                <img src="https://cdn.jsdelivr.net/gh/Raaxxy/Trade-plaza@main/Tradeplaza/media/logo.jpeg" class="h-8" alt="TradePlaza Logo" />
                <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">TradePlaza</span>
            </a>
            <div class="flex md:order-2">
                <button id="searchButton"type="button" data-collapse-toggle="navbar-search" aria-controls="navbar-search" aria-expanded="false" class="md:hidden text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-2.5 me-1">
                    <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                    </svg>
                    <span class="sr-only">Search</span>
                </button>
                <form id="searchForm" method="get" action="{% url 'item:items' %}">
                    <div class="relative hidden md:block">
                        <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                            </svg>
                            <span class="sr-only">Search icon</span>
                        </div>
                        <input name="query" type="text" value="{{ query }}" placeholder="Search TradePlaza..." class="block w-full p-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" >
                    </div>  
                </form>
                <button data-collapse-toggle="navbar-search" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-search" aria-expanded="false">
                    <span class="sr-only">Open main menu</span>
                    <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
                    </svg>
                </button>
            </div>
            <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-2" id="navbar-search">
                <form method="get" action="{% url 'item:items' %}">
                    <div class="relative mt-3 md:hidden">
                        <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                            </svg>
                        </div>
                        <input type="text" name="query" value="{{ query }}" placeholder="Search TradePlaza..." class="block w-full p-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                    </div>
                </form>
                    <ul class="flex flex-col p-4 md:p-0 mt-4 font-medium border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                        <li>
                            <a href="/" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Home</a>
                        </li>
                        <li>
                            <a href="{% url 'core:about' %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">About</a>
                        </li>
                        {% if request.user.is_authenticated %}
                                <li>
                                    <a href="{% url 'item:new' %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">List Items</a>
                                </li>
                                <li>
                                    <button id="dropdownNavbarLink" data-dropdown-toggle="dropdownNavbar" class="flex items-center justify-between w-full py-2 px-3 text-gray-900 hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 md:w-auto dark:text-white md:dark:hover:text-blue-500 dark:focus:text-white dark:hover:bg-gray-700 md:dark:hover:bg-transparent">
                                        <img src="https://freesvg.org/img/abstract-user-flat-4.png" class="h-[25px]" alt="user-pfp" /> &nbsp;
                                        Welcome, {{ request.user.username }}!
                                        <svg class="w-2.5 h-2.5 ms-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
                                        </svg>
                                    </button>
                                    <div id="dropdownNavbar" class="flex-none justify-end  absolute z-10 hidden w-56 mt-2 rounded-md shadow-md bg-gray-800">
                                        <ul class="p-1">
                                            <li>
                                                <a href="{% url 'dashboard:index' %}" class="flex justify-center items-center rounded-md block px-4 py-2 text-sm text-white hover:bg-gray-700 ">Dashboard</a>
                                            </li>
                                            <li>
                                                <a href="{% url 'conversation:inbox' %}" class="flex justify-center items-center rounded-md block px-4 py-2 text-sm text-white hover:bg-gray-700 ">Inbox</a>
                                            </li>
                                        </ul>
                                        <div class="p-1 border-t">
                                            <a href="{% url 'core:logout' %}" class="block rounded-md px-4 py-2 text-sm text-white bg-red-500 hover:bg-red-600 flex justify-center items-center">
                                                {% csrf_token %}
                                                Sign out
                                            </a>
                                        </div>
                                    </div> 
                                </li>    
                            {% else %}
                                <li>
                                    <a href="{% url 'core:signup' %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Sign up</a>
                                </li>
                                <li>
                                    <a href="{% url 'core:login' %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Sign in</a>
                                </li>  
                            {% endif %}
                    </ul>
            </div>
        </div>    
    </nav>
  
    <div>
        {% block content %}

        {% endblock %}
    </div>

    <footer class="bg-gray-900 mt-auto">
        <div class="w-full max-w-screen-xl mx-auto p-4 md:py-8">
            <div
                class="flex flex-col sm:flex-row sm:items-center sm:justify-between sm:flex sm:items-center sm:justify-between">
                <a href="/"
                    class="flex items-center mb-4 sm:mb-0 space-x-3 rtl:space-x-reverse">
                    <img src="https://cdn.jsdelivr.net/gh/Raaxxy/Trade-plaza@main/Tradeplaza/media/logo.jpeg" class="h-8" alt="TradePlaza Logo" />
                    <span class="self-center text-2xl font-semibold text-white whitespace-nowrap ">TradePlaza</span>
                </a>
                <ul
                    class="flex flex-wrap items-center mb-6 text-sm font-medium text-white sm:mb-0 ">
                    <li>
                        <a href="{% url 'core:about' %}"
                            class="hover:underline me-4 md:me-6">About</a>
                    </li>
                    <li>
                        <a href="{% url 'core:policy' %}"
                            class="hover:underline me-4 md:me-6">Privacy
                            Policy</a>
                    </li>
                    <li>
                        <a href="{% url 'core:license' %}"
                            class="hover:underline me-4 md:me-6">Licensing</a>
                    </li>
                    <li>
                        <a target="_blank" href="https://github.com/raaxxy"
                            class="hover:underline">Contact</a>
                    </li>
                </ul>
            </div>
            <hr class="my-6 border-gray-400 sm:mx-auto lg:my-8" />
            <span
                class="block text-sm text-white sm:text-center">© 2024 <a
                    href="#"
                    class="hover:underline">TradePlaza™</a>. All Rights Reserved.</span>
        </div>
    </footer>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const toggleButtons = document.querySelectorAll('[data-collapse-toggle]');
            var dropdownButton = document.getElementById('dropdownNavbarLink');
            var dropdownMenu = document.getElementById('dropdownNavbar');
            var searchButton = document.getElementById('searchButton');

            var searchForm = document.getElementById('searchForm')
            var menuButton = document.querySelector('[data-collapse-toggle="navbar-search"]');
      
            toggleButtons.forEach(button => {
              button.addEventListener('click', function () {
                const targetId = this.getAttribute('data-collapse-toggle');
                const targetElement = document.getElementById(targetId);
                if (targetElement) {
                  targetElement.classList.toggle('hidden');
                }
              });
            });
            dropdownButton.addEventListener('click', function () {
                dropdownMenu.classList.toggle('hidden');
            });
            searchButton.addEventListener('click', function () {
                
                searchForm.classList.toggle('hidden');
            });
            
            menuButton.addEventListener('click', function () {
                menu.classList.toggle('hidden');
            });
            
        }); 

    </script>
</body>

</html>

Tradeplaza/core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %}Welcome{% endblock %}
{% block content %}
<div class="justify-center items-center">
    <div class="w-full px-6 py-12 bg-gray-900 flex flex-col items-center justify-center">
        <h2 class="mb-12 text-3xl font-semibold text-white text-center flex">Newest items</h2>
        <div class="grid md:grid-cols-1 lg:grid-cols-3 gap-3 flex">
            {% for item in random_items %}
            <div class="w-full max-w-sm border border-gray-200 rounded-lg shadow bg-gray-800 dark:border-gray-700 hover:shadow-md transition-shadow">
                <a href="{% url 'item:detail' item.id%}">
                    <img class="p-8 rounded-t-lg w-full h-[280px]"
                        src="{{item.image.url}}" alt="{{item.name}}" />
                </a>
                <div class="px-5 pb-5">
                    <a href="{% url 'item:detail' item.id%}">
                        <h5 class="text-xl font-semibold tracking-tight text-gray-900 dark:text-white">{{item.name}}</h5>
                    </a>
                    <div class="flex items-center mt-2.5 mb-5">
                        <div
                            class="flex items-center space-x-1 rtl:space-x-reverse">
                            <svg class="w-4 h-4 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                            </svg>
                            <svg class="w-4 h-4 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                            </svg>
                            <svg class="w-4 h-4 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                            </svg>
                            <svg class="w-4 h-4 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                            </svg>
                            <svg class="w-4 h-4 text-gray-200 dark:text-gray-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                            </svg>
                        </div>
                        <span class="bg-blue-100 text-blue-800 text-xs font-semibold px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800 ms-3">5.0</span>
                    </div>
                    <div class="flex items-center justify-between">
                        <span class="text-3xl font-bold text-gray-900 dark:text-white">${{item.price}}</span>
                        <a href="{% url 'conversation:new' item.id %}"
                            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Contact Seller
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock  %}

Tradeplaza/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<section class="bg-gray-900">
    <div class="flex flex-col items-center justify-center px-4 py-4 mx-auto h-screen lg:py-0">
        <div class="w-full rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 bg-gray-800 dark:border-gray-700">
            <div class="p-4 space-y-4 md:space-y-6 sm:p-6">
                <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                    Sign In
                </h1>
                <form class="space-y-4 md:space-y-6" method="post" action=".">
                    {% csrf_token %}

                    <div>
                        <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your username</label>
                        {{ form.username }}
                    </div>
                    <div>
                        <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Password</label>
                        {{ form.password }}
                    </div>
                
                    {% if form.errors or form.non_field_errors%}
                        <div class="mb-3 p-6 bg-red-100 rounded-xl">
                            {% for field in form %}
                                {{field.errors}}
                            {% endfor %}
                            {{form.non_field_errors}}
                        </div>
                    {% endif %}
                    <button class="w-full text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">Log in</button>
                    <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                        Don't have an account? <a href="{% url 'core:signup' %}"
                            class="font-medium text-primary-600 hover:underline dark:text-primary-500">Join us today!</a>
                    </p>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock  %}